// AUTO-GENERATED by Seefar from the live Supabase schema — do not edit by hand.
// Every Supabase query in this app is type-checked against the fields below.
// If the schema changes, re-run the Supabase integration to refresh this file.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.15"
  }
  public: {
    Tables: {
      achievements: {
        Row: {
          badge: string | null
          created_at: string | null
          description: string | null
          icon: string | null
          id: string
          isUnlocked: boolean | null
          title: string
          unlockedDate: string | null
          updated_at: string | null
          userId: string
        }
        Insert: {
          badge?: string | null
          created_at?: string | null
          description?: string | null
          icon?: string | null
          id?: string
          isUnlocked?: boolean | null
          title: string
          unlockedDate?: string | null
          updated_at?: string | null
          userId: string
        }
        Update: {
          badge?: string | null
          created_at?: string | null
          description?: string | null
          icon?: string | null
          id?: string
          isUnlocked?: boolean | null
          title?: string
          unlockedDate?: string | null
          updated_at?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "achievements_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      activities: {
        Row: {
          calories: number | null
          created_at: string | null
          distance: number | null
          duration: number | null
          endTime: string | null
          id: string
          intensity: string | null
          notes: string | null
          pace: number | null
          startTime: string | null
          status: string | null
          timestamp: string | null
          type: string
          updated_at: string | null
          userId: string
        }
        Insert: {
          calories?: number | null
          created_at?: string | null
          distance?: number | null
          duration?: number | null
          endTime?: string | null
          id?: string
          intensity?: string | null
          notes?: string | null
          pace?: number | null
          startTime?: string | null
          status?: string | null
          timestamp?: string | null
          type: string
          updated_at?: string | null
          userId: string
        }
        Update: {
          calories?: number | null
          created_at?: string | null
          distance?: number | null
          duration?: number | null
          endTime?: string | null
          id?: string
          intensity?: string | null
          notes?: string | null
          pace?: number | null
          startTime?: string | null
          status?: string | null
          timestamp?: string | null
          type?: string
          updated_at?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "activities_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      daily_stats: {
        Row: {
          activityCount: number | null
          created_at: string | null
          date: string
          id: string
          totalCalories: number | null
          totalDistance: number | null
          totalDuration: number | null
          updated_at: string | null
          userId: string
        }
        Insert: {
          activityCount?: number | null
          created_at?: string | null
          date: string
          id?: string
          totalCalories?: number | null
          totalDistance?: number | null
          totalDuration?: number | null
          updated_at?: string | null
          userId: string
        }
        Update: {
          activityCount?: number | null
          created_at?: string | null
          date?: string
          id?: string
          totalCalories?: number | null
          totalDistance?: number | null
          totalDuration?: number | null
          updated_at?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "daily_stats_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      goals: {
        Row: {
          created_at: string | null
          endDate: string | null
          id: string
          progress: number | null
          startDate: string | null
          status: string | null
          target: string | null
          targetValue: number | null
          type: string
          updated_at: string | null
          userId: string
        }
        Insert: {
          created_at?: string | null
          endDate?: string | null
          id?: string
          progress?: number | null
          startDate?: string | null
          status?: string | null
          target?: string | null
          targetValue?: number | null
          type: string
          updated_at?: string | null
          userId: string
        }
        Update: {
          created_at?: string | null
          endDate?: string | null
          id?: string
          progress?: number | null
          startDate?: string | null
          status?: string | null
          target?: string | null
          targetValue?: number | null
          type?: string
          updated_at?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "goals_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      seefar_metadata: {
        Row: {
          app_id: string
          app_name: string
          created_at: string | null
          id: string
          seefar_origin: boolean | null
        }
        Insert: {
          app_id: string
          app_name: string
          created_at?: string | null
          id?: string
          seefar_origin?: boolean | null
        }
        Update: {
          app_id?: string
          app_name?: string
          created_at?: string | null
          id?: string
          seefar_origin?: boolean | null
        }
        Relationships: []
      }
      users: {
        Row: {
          age: number | null
          avatar: string | null
          created_at: string | null
          email: string
          fitnessGoal: string | null
          height: number | null
          id: string
          joinDate: string | null
          name: string | null
          totalCalories: number | null
          totalDistance: number | null
          totalWorkouts: number | null
          updated_at: string | null
          weight: number | null
        }
        Insert: {
          age?: number | null
          avatar?: string | null
          created_at?: string | null
          email: string
          fitnessGoal?: string | null
          height?: number | null
          id?: string
          joinDate?: string | null
          name?: string | null
          totalCalories?: number | null
          totalDistance?: number | null
          totalWorkouts?: number | null
          updated_at?: string | null
          weight?: number | null
        }
        Update: {
          age?: number | null
          avatar?: string | null
          created_at?: string | null
          email?: string
          fitnessGoal?: string | null
          height?: number | null
          id?: string
          joinDate?: string | null
          name?: string | null
          totalCalories?: number | null
          totalDistance?: number | null
          totalWorkouts?: number | null
          updated_at?: string | null
          weight?: number | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
